/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplicationctest_JniUtils */

#ifndef _Included_com_example_myapplicationctest_JniUtils
#define _Included_com_example_myapplicationctest_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplicationctest_JniUtils
 * Method:    getLinuxVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplicationctest_JniUtils_getLinuxVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myapplicationctest_JniUtils
 * Method:    passArrayMethod
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_myapplicationctest_JniUtils_passArrayMethod
  (JNIEnv *, jclass , jintArray);

/*
 * Class:     com_example_myapplicationctest_JniUtils
 * Method:    createArrayMethod
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_myapplicationctest_JniUtils_createArrayMethod
  (JNIEnv *, jclass , jint);

#ifdef __cplusplus
}
#endif
#endif
